spring:
  application:
    name: Tec Flix API
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/tecflix_db?useTimezone=true&serverTimezone=UTC # url database
    username: developer # user database
    password: 123456 # user password
  jpa:
    open-view: false
    hibernate:
      ddl-auto: update # https://stackoverflow.com/questions/438146/what-are-the-possible-values-of-the-hibernate-hbm2ddl-auto-configuration-and-wha
    show-sql: false