spring:
  application:
    name: Tec Flix API
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/tec_flix_db?useTimezone=true&serverTimezone=UTC
    username: developer
    password: 123456
  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: update
    show-sql: false